# Generated by Django 4.2.2 on 2023-07-04 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoTestCase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='font',
            field=models.CharField(default='Arial', max_length=255, verbose_name='font'),
        ),
        migrations.AddField(
            model_name='log',
            name='size',
            field=models.FloatField(default=0.4, verbose_name='size'),
        ),
    ]
